spring:
  datasource:
    url: jdbc:postgresql://localhost:32768/mydatabase
    driver-class-name: org.postgresql.Driver
    username: myuser
    password: secret
  liquibase:
    #  enabled: true
    change-log: db/changelog/changelog-master.yml
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true
        globally_quoted_identifiers: true
        globally_quoted_identifiers_skip_column_definitions: true
  docker:
    compose:
      file: docker-compose.yaml