spring:
  datasource:
    url: jdbc:postgresql://localhost:32768/mydatabase
    driver-class-name: org.postgresql.Driver
    username: myuser
    password: secret
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true
  docker:
    compose:
      file: docker-compose.yaml